### ISSUE TITLE
Failure to find com.google.jstestdriver:jstestdriver:jar:1.3.4.b

### ISSUE THREAD

**Issue by coderbyheart** [stefanscheidt/js-fadein#1]
Hoi,

ich versuche gerade gemäß der README die Tests zum Laufen zu bekommen.
Leider schlägt
`mvn -e clean install -Pintegration`
mit dieser Ausgabe fehl: https://gist.github.com/3743785

Ausgabe der `misc/install.sh`:
https://gist.github.com/3743793

System: Arch Linux

```
$ mvn -version
Apache Maven 3.0.4 (rNON-CANONICAL_2012-01-24_13-02_root; 2012-01-24 14:02:02+0100)
Maven home: /opt/maven
Java version: 1.7.0_07, vendor: Oracle Corporation
Java home: /opt/java/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "3.5.3-1-arch", arch: "amd64", family: "unix"
```

Was mache ich falsch?

**Comment by stefanscheidt** [comment]
Hmm, strange. Can't reproduce on my machine. Can you try to delete `/home/m/.m2/repository/com/google/jstestdriver/jstestdriver/1.3.4.b/`, then run `misc/install.sh` again and then `mvn -e clean install -Pintegration`? Does this cause the same problem?

Upps. Du hast ja in deutsch geschrieben. Sorry. Alles weitere dann in deutsch...

**Comment by coderbyheart** [comment]
Das ändert leider nichts:
https://gist.github.com/3746021

```
[m@nanshe js-fadein]$ ls -la /home/m/.m2/repository/com/google/jstestdriver/jstestdriver/1.3.4.b
insgesamt 20
drwxr-xr-x 2 m m 4096 18. Sep 23:25 .
drwxr-xr-x 3 m m 4096 18. Sep 23:25 ..
-rw-r--r-- 1 m m  375 18. Sep 23:25 jstestdriver-1.3.4.b.jar.lastUpdated
-rw-r--r-- 1 m m  481 18. Sep 23:25 jstestdriver-1.3.4.b.pom
-rw-r--r-- 1 m m  181 18. Sep 23:25 _maven.repositories
```

Passt das?

**Comment by stefanscheidt** [comment]
Hmm. Das verstehe ich leider noch nicht. Ändere doch bitte mal in `pom.xml` den Eintrag

```
<dependencies>
    <dependency>
        <groupId>com.google.jstestdriver</groupId>
        <artifactId>jstestdriver</artifactId>
        <version>1.3.4.b</version>
        <scope>test</scope>
    </dependency>
</dependencies>
```

in

```
<dependencies>
    <dependency>
        <groupId>com.google.jstestdriver</groupId>
        <artifactId>jstestdriver</artifactId>
        <version>1.3.4.b</version>
        <scope>system</scope>
        <systemPath>${basedir}/misc/JsTestDriver.jar</systemPath>
    </dependency>
</dependencies>
```

Das ist zwar in gewisser Weise ein unschöner Hack, aber es sollte zunächst das Problem lösen, dass die Dependency zu jstestdriver offenbar nicht aufgelöst werden kann.

**Comment by coderbyheart** [comment]
```
$ git diff
diff --git a/pom.xml b/pom.xml
index de7ebd6..ef99acb 100644
--- a/pom.xml
+++ b/pom.xml
@@ -53,7 +53,8 @@
             <groupId>com.google.jstestdriver</groupId>
             <artifactId>jstestdriver</artifactId>
             <version>1.3.4.b</version>
-            <scope>test</scope>
+            <scope>system</scope>
+            <systemPath>${basedir}/misc/JsTestDriver.jar</systemPath>
         </dependency>
     </dependencies>
```

Ergebnis: https://gist.github.com/3748892

```
[ERROR] Failed to execute goal com.googlecode.jstd-maven-plugin:jstd-maven-plugin:1.3.2.5:test (run-unit-tests) on    project js-fadein: Failed to parse results -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.googlecode.jstd-maven-plugin:jstd-maven-plugin:1.3.2.5:test (run-unit-tests) on project js-fadein: Failed to parse results
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
```

**Comment by stefanscheidt** [comment]
OK. Das Dependency-Problem bezüglich jstestdriver ist zumindest schon mal provisorisch umschifft. Das aktuelle Problem könnte nun noch daran liegen, dass es auf Deinem System kein `chrome` in Deinem Pfad gibt. Kannst Du bitte den Build nochmals mit `mvn -e clean install -Pintegration -Dbrowser=<Ausgabe von 'which chromium'>` starten? (Die Option `-Dbrowser='which chromium'` wird vermutlich nicht funktionieren.)

Bitte entschuldige das Rumgefrickel. Deine Logausgaben lassen vermuten, dass Du mit einer frischen Maven-Installation gearbeitet hast. Unter dieser Annahme ist mir noch unerklärlich, warum Du bis zum letzten Versuch Dependency-Probleme mit jstestdriver hattest. Ich kann das leider nicht reproduzieren ...

**Comment by coderbyheart** [comment]
Ich musst beim Posten die Backticks in Apostrophe ändern …
So geht es jetzt. Vielen Dank!
